=== CesiumGS/3d-tiles/specification/schema/tileset.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "tileset.schema.json",
    "title": "Tileset",
    "type": "object",
    "description": "A 3D Tiles tileset.",
    "allOf": [
        {
            "$ref": "rootProperty.schema.json"
        }
    ],
    "properties": {
        "asset": {
            "description": "Metadata about the entire tileset.",
            "$ref": "asset.schema.json"
        },
        "properties": {
            "type": "object",
            "description": "A dictionary object of metadata about per-feature properties.",
            "additionalProperties": {
                "$ref": "properties.schema.json"
            },
            "deprecated": true
        },
        "schema": {
            "allOf": [
                {
                    "$ref": "schema.schema.json"
                }
            ],
            "description": "An object defining classes and enums."
        },
        "schemaUri": {
            "type": "string",
            "description": "The URI (or IRI) of the external schema file.",
            "format": "iri-reference"
        },
        "statistics": {
            "allOf": [
                {
                    "$ref": "statistics.schema.json"
                }
            ],
            "description": "An object containing statistics about entities."
        },
        "groups": {
            "type": "array",
            "description": "An array of groups.",
            "items": {
                "$ref": "group.schema.json"
            },
            "minItems": 1
        },
        "metadata": {
            "allOf": [
                {
                    "$ref": "metadataEntity.schema.json"
                }
            ],
            "description": "Tileset metadata."            
        },
        "geometricError": {
            "type": "number",
            "description": "The error, in meters, introduced if this tileset is not rendered. At runtime, the geometric error is used to compute screen space error (SSE), i.e., the error measured in pixels.",
            "minimum": 0
        },
        "root": {
            "description": "The root tile.",
            "$ref": "tile.schema.json"
        },
        "extensionsUsed": {
            "type": "array",
            "description": "Names of 3D Tiles extensions used somewhere in this tileset.",
            "items": {
                "type": "string"
            },
            "uniqueItems": true,
            "minItems": 1
        },
        "extensionsRequired": {
            "type": "array",
            "description": "Names of 3D Tiles extensions required to properly load this tileset.",
            "items": {
                "type": "string"
            },
            "uniqueItems": true,
            "minItems": 1
        },
        "extensions": {},
        "extras": {}
    },
    "required": [
        "asset",
        "geometricError",
        "root"
    ],
    "oneOf": [
        {
            "description": "External schema, if any.",
            "not": {
                "required": [
                    "schema"
                ]
            }
        },
        {
            "description": "Internal schema, if any.",
            "not": {
                "required": [
                    "schemaUri"
                ]
            }
        }
    ]
}

=== CesiumGS/3d-tiles/extensions/3DTILES_implicit_tiling/examples/sparseOctree/tileset.json
{
  "asset": {
    "version": "1.0"
  },
  "geometricError": 10000,
  "extensionsUsed": [
    "3DTILES_implicit_tiling"
  ],
  "extensionsRequired": [
    "3DTILES_implicit_tiling"
  ],
  "root": {
    "boundingVolume": {
      "region": [-1.318, 0.697, -1.319, 0.698, 0, 20]
    },
    "refine": "ADD",
    "geometricError": 5000,
    "content": {
      "uri": "content/{level}/{x}/{y}/{z}.b3dm"
    },
    "extensions": {
      "3DTILES_implicit_tiling": {
        "subdivisionScheme": "OCTREE",
        "subtreeLevels": 2,
        "maximumLevel": 5,
        "subtrees": {
          "uri": "subtrees/{level}/{x}/{y}/{z}.subtree"
        }
      }
    }
  }
}

=== CesiumGS/3d-tiles/extensions/3DTILES_dynamic/exampleTileset.json
{
  "extensions" : {
    "3DTILES_dynamic" : {
      "dimensions" : [ {
        "name" : "exampleTimeStamp",
        "keySet" : [ "2025-09-25", "2025-09-26" ]
      }, {
        "name" : "exampleRevision",
        "keySet" : [ "revision0", "revision1" ]
      } ]
    }
  },
  "asset" : {
    "version" : "1.1"
  },
  "geometricError" : 2.0,
  "root" : {
    "refine": "REPLACE",
    "boundingVolume" : {
      "box" : [ 0.5, 0.5, 0.5, 0.5, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.5 ]
    },
    "geometricError" : 1.0,
    "content": {
      "uri": "exampleContent.json"
    }
  }
}

=== CesiumGS/3d-tiles/extensions/3DTILES_implicit_tiling/examples/fullQuadtree/tileset.json
{
  "asset": {
    "version": "1.0"
  },
  "geometricError": 10000,
  "extensionsUsed": [
    "3DTILES_implicit_tiling"
  ],
  "extensionsRequired": [
    "3DTILES_implicit_tiling"
  ],
  "root": {
    "boundingVolume": {
      "region": [-1.318, 0.697, -1.319, 0.698, 0, 20]
    },
    "refine": "ADD",
    "geometricError": 5000,
    "content": {
      "uri": "content/{level}/{x}/{y}.b3dm"
    },
    "extensions": {
      "3DTILES_implicit_tiling": {
        "subdivisionScheme": "QUADTREE",
        "subtreeLevels": 3,
        "maximumLevel": 2,
        "subtrees": {
          "uri": "subtrees/{level}/{x}/{y}.subtree"
        }
      }
    }  
  }
}

=== CesiumGS/3d-tiles/extensions/3DTILES_metadata/examples/terrainpack/terrainpack-tileset.json
{
  "asset": {
    "version": "1.0"
  },
  "geometricError": 32768.0,
  "root": {
    "boundingVolume": {
      "region": [
        -1.7074684758166778,
        0.54359911736543987,
        -1.7067080890553497,
        0.54416505068266019,
        203.89508305676281,
        253.11363569926471
      ]
    },
    "geometricError": 32768.0,
    "refine": "ADD",
    "extensions": {
      "3DTILES_layers": {
        "contents": [
          {
            "layer": "watermask",
            "uri": "watermask.3tz",
            "mimeType": "application/vnd.maxar.archive.3tz+zip"
          },
          {
            "layer": "org",
            "uri": "org.3tz",
            "mimeType": "application/vnd.maxar.archive.3tz+zip"
          }
        ]
      }
    }
  },
  "extensionsRequired": [
    "3DTILES_layers",
    "3DTILES_metadata",
    "MAXAR_layer_content_3tz"
  ],
  "extensionsUsed": [
    "3DTILES_layers",
    "3DTILES_metadata",
    "MAXAR_extent",
    "MAXAR_layer_content_3tz"
  ],
  "extensions": {
    "MAXAR_extent": {
      "uri": "extent.geojson"
    },
    "3DTILES_metadata": {
      "tileset": {
        "class": "WFFDataPackageClass",
        "properties": {
          "content_type": "MIXED",
          "created": "2020-10-28T13:15:07.511400Z",
          "geometry_model": "MIXED",
          "id": "4b086de5-82c4-4674-8097-9a8f240ccfee",
          "provider": "Maxar",
          "runtime_enabled": false,
          "schema": "wff/1",
          "texture_features": [],
          "wff_version": "1.0"
        }
      },
      "classes": {
        "WFFDatasetClassA": {
          "properties": {
            "capture_platform": {
              "type": "STRING"
            },
            "capture_sensor": {
              "type": "STRING"
            },
            "content_type": {
              "type": "STRING"
            },
            "created": {
              "type": "STRING"
            },
            "geometry_model": {
              "type": "STRING"
            },
            "id": {
              "type": "STRING"
            },
            "provider": {
              "type": "STRING"
            },
            "runtime_enabled": {
              "type": "BOOLEAN"
            },
            "schema": {
              "type": "STRING"
            },
            "texture_features": {
              "type": "ARRAY",
              "componentType": "INT32"
            },
            "wff_version": {
              "type": "STRING"
            }
          }
        },
        "WFFDatasetClassB": {
          "properties": {
            "capture_platform": {
              "type": "STRING"
            },
            "capture_sensor": {
              "type": "STRING"
            },
            "content_type": {
              "type": "STRING"
            },
            "created": {
              "type": "STRING"
            },
            "geometry_model": {
              "type": "STRING"
            },
            "id": {
              "type": "STRING"
            },
            "provider": {
              "type": "STRING"
            },
            "runtime_enabled": {
              "type": "BOOLEAN"
            },
            "schema": {
              "type": "STRING"
            },
            "texture_features": {
              "type": "ARRAY",
              "componentType": "STRING"
            },
            "wff_version": {
              "type": "STRING"
            }
          }
        },
        "WFFDataPackageClass": {
          "properties": {
            "content_type": {
              "type": "STRING"
            },
            "created": {
              "type": "STRING"
            },
            "geometry_model": {
              "type": "STRING"
            },
            "id": {
              "type": "STRING"
            },
            "provider": {
              "type": "STRING"
            },
            "runtime_enabled": {
              "type": "BOOLEAN"
            },
            "schema": {
              "type": "STRING"
            },
            "texture_features": {
              "type": "ARRAY",
              "componentType": "INT32"
            },
            "wff_version": {
              "type": "STRING"
            }
          }
        }
      },
      "extras": {
        "draftVersion": "0.0.0"
      }
    },
    "3DTILES_layers": {
      "layers": {
        "org": {
          "class": "WFFDatasetClassB",
          "name": "Ft Hood - Surface",
          "properties": {
            "capture_platform": {
              "values": ["SATELLITE"]
            },
            "capture_sensor": "ELECTRO_OPTICAL",
            "content_type": "MESH",
            "created": "2020-10-28T13:15:07.171481Z",
            "geometry_model": "BARE_EARTH",
            "id": "56b7b942-e2c2-457c-b56b-a1992ac9c204",
            "provider": "Maxar",
            "runtime_enabled": false,
            "schema": "wff/1",
            "texture_features": [
              "r3dm::cdm_difference",
              "r3dm::date_avg",
              "r3dm::date_first",
              "r3dm::date_last",
              "r3dm::image_count",
              "r3dm::ndvi",
              "r3dm::ndvi_cnt",
              "r3dm::ndvi_max",
              "r3dm::ndvi_min",
              "r3dm::security",
              "r3dm::uncertainty_ce90",
              "r3dm::uncertainty_le90",
              "r3dm::universal_mix"
            ],
            "wff_version": "1.0"
          }
        },
        "watermask": {
          "class": "WFFDatasetClassA",
          "name": "Ft Hood - Watermask",
          "properties": {
            "capture_platform": "SATELLITE",
            "capture_sensor": "ELECTRO_OPTICAL",
            "content_type": "VECTOR",
            "created": "2020-10-28T13:15:07.462467Z",
            "geometry_model": "OBJECTS",
            "id": "cc18fa2f-1c1a-4f05-8c3e-9d685a56bd0f",
            "provider": "Maxar",
            "runtime_enabled": false,
            "schema": "wff/1",
            "texture_features": [],
            "wff_version": "1.0"
          }
        }
      },
      "extras": {
        "draftVersion": "0.0.0"
      }
    }
  }
}
